version: "3.9"
services: 
  # apache webserver
  apache:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # map volumes
      - ./htdocs:/var/www/html
    ports:
      - 80:80
    networks:
      - phpLocalNetwork
  # mariadb server
  mariadb:
    image: mariadb
    environment:
      # database en root password
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: console_source
    ports:
      - 3306:3306
    networks:
      - phpLocalNetwork
  # phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mariadb:db
    ports:
     - 8080:80
    networks:
      - phpLocalNetwork
networks:
  phpLocalNetwork: